- router/pkg/qrouter/proxy.go
Fix the bug on comparing the length of columns slice when adding sharding rule for proxy router
> fix(router): compare the number of columns when adding sharding rule

- coordinator/provider/coordinator.go
Fixed panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
spqr-coordinator-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8cd99e]
spqr-coordinator-1  | 
spqr-coordinator-1  | goroutine 67 [running]:
spqr-coordinator-1  | github.com/pg-sharding/spqr/router/pkg/route.(*Route).Params(0x0)
spqr-coordinator-1  | 	/home/go/src/github.com/pg-sharding/spqr/router/pkg/route/route.go:59 +0x5e
spqr-coordinator-1  | github.com/pg-sharding/spqr/router/pkg/client.(*PsqlClient).Auth(0xc0005b8db8, 0xda0f26?)
spqr-coordinator-1  | 	/home/go/src/github.com/pg-sharding/spqr/router/pkg/client/client.go:511 +0x30a
spqr-coordinator-1  | github.com/pg-sharding/spqr/coordinator/provider.(*qdbCoordinator).ProcClient(0xc00007e140?, {0xeb1430, 0xc000038040}, …
```
> fix: add a mock router to avoid panic in the coordinator client process

- config-example/1shardproxy.toml
- config-example/2shardproxy.yaml
- config-example/localrouter.yaml
- pkg/config/router.go
- router/pkg/datashard/conn_pool.go
- router/pkg/instance.go
- router/pkg/qrouter/local.go
Implement target session attrs option and policies
for backend connections. Now ew can specify in shard`s
config to match replica/primary hosts while acquiring
new connections
> Add target-session-attrs option to shard config

- balancer/app/app.go
- cmd/balancer/main.go
- pkg/config/tls.go
- router/pkg/datashard/conn_pool.go
- router/pkg/instance.go
It was impossible for the router to connect to shards using a root certificate.
It works: 
```
root@denchick-spqr01h:/spqr# psql "host=localhost sslmode=disable user=sbtest dbname=sbtest port=6432"
psql (14.5 (Ubuntu 14.5-201-yandex.52547.2fabebd33c))
Type "help" for help.
sbtest=> select * from articles;
NOTICE: send query to shard(s) : shard01,shard02
id 
----
(0 rows)
```
SPQR logs:
```
root@denchick-spqr01h:/spqr# ./spqr-router -c router.yaml run
2022/11/07 06:36:45 Running config: {
"log_level": "",
"host": "localhost",
"router_port": "6432",
"admin_console_port": "7432",
"grpc_api_port": "7000",
"world_shard_fallback": false,
"show_notice_messages": true,
"auto_conf": "",
"init_sql": "init.sql",
"under_coordinator": false,
"router_mode": "PROXY",
"jaeger_url": "",
"frontend_rules": …
```
> Handle `sslmode` correctly

- pkg/client/client.go
- pkg/config/router.go
- router/pkg/client/client.go
- router/pkg/frontend.go
- router/pkg/instance.go
- router/pkg/qrouter/proxy.go
- router/pkg/qrouter/proxy_routing.go
- router/pkg/qrouter/qrouter.go
- router/pkg/rulerouter/relay.go
Process sync message correctly in cases when there is no active backend connections to any shard, instead of replying with error 'too complex to parse'. This fixed the case when sync message is issued right after parse message, or similar, in which router fill fail to 'route' sync to shard, because this is un-routabale messafe.
> Support sync messages in multi-shard setup

- qdb/ops/ops.go
- router/pkg/qrouter/proxy_routing.go
- test/regress/tests/router/expected/shard_routing.out
- test/regress/tests/router/sql/shard_routing.sql
All columns in query should be considered in context of its table,
to distinguish composite join/select queries routing schemas
For example,
SELECT * FROM a join b WHERE a.c1 = <val> and b.c2 = <val>
and
SELECT * FROM a join b WHERE a.c1 = <val> and a.c2 = <val>
can be routed with different rules
Also, this test now works, as we remember each table alias in parse-time:
```
postgres=# select * from t1 a where i <= 30;
i
----
22
(1 row)
postgres=# select * from t1 a where a.i <= 30;
ERROR:  too complex query to parse
```
> Group columns by its relations name, to properly route queries

- qdb/memqdb.go
- router/pkg/qrouter/proxy_routing.go
- test/regress/tests/router/expected/shard_routing.out
- test/regress/tests/router/sql/shard_routing.sql
Add logic for `INSERT FROM SELECT` routing e.g.
```
postgres=# select * from t1;
i
----
1
10
1
10
22
(5 rows)
postgres=# insert into t1 select * from t1 where i = 10 returning *;
i
----
10
10
(2 rows)
INSERT 0 2
postgres=# ^C
```
now works
> Add routing on insert from select statements

- config-example/router.yaml
- pkg/conn/auth.go
- pkg/conn/instance.go
- router/pkg/datashard/conn_pool.go
- router/pkg/datashard/datashard.go
- router/pkg/rulerouter/relay.go
Include client and/or shard ids to TLS-related log messages. Also, fix config-exmpales/router.yaml to show that only root ca path is required to connect to backends (shard) while server_key file is not
> Enhance router TLS-related log messages.

- pkg/config/router.go
- router/pkg/qrouter/proxy_routing.go
To set up failed-to-match logic in router
> Add default_route_behaviour setting

- balancer/pkg/mock.go
- coordinator/provider/coordinator.go
- qdb/etcdqdb.go
- router/datashard/datashard.go
- router/qrouter/proxy_routing.go
- router/rule/rulemgr.go
- router/rulerouter/relay.go
- router/rulerouter/rulerouter.go
```
ERROR: 2023/06/27 09:21:30.003734 failed to route frontend for client: route for user:monitor and db:postgres is unconfigured in
```
> fix typos, minor log fixes

- cmd/mover/main.go
- coordinator/provider/coordinator.go
- docker/coordinator/cfg.yaml
- docker/coordinator/shard_data.yaml
- docker/shard/bin/setup
- docker/tests/bin/move.sh
- examples/coordinator.yaml
- pkg/config/coordinator.go
- pkg/config/data_transfers.go
- pkg/datatransfers/data_transfers.go
- pkg/datatransfers/shard_data.yaml
- qdb/etcdqdb.go
- qdb/memqdb.go
- qdb/qdb.go
- test/feature/conf/coordinator.yaml
- test/feature/conf/shard_data.yaml
- test/feature/features/move.feature
- test/feature/spqr_test.go
- test/feature/testutil/docker_composer.go
Coordinator command "MOVE KEY RANGE kr TO sh" now moves data between shards
> Data transfer

- .github/workflows/tests.yaml
We can also split Coordinator test as the longest one (about 12 min)
> Run job on each feature tests

- router/client/client.go
- router/instance.go
- router/rulerouter/rulerouter.go
essentially fixes https://github.com/pg-sharding/spqr/issues/255
> Unite admin-console/psql-console pre-routing logic.

- coordinator/provider/coordinator.go
- pkg/clientinteractor/interactor.go
- pkg/models/topology/routers.go
- qdb/etcdqdb.go
- qdb/memqdb.go
- qdb/qdb.go
- router/instance.go
- test/regress/tests/console/expected/show_routers.out
```
spqr-consolds=> show routers;
show routers       | status
--------------------------+--------
router r1-localhost:7010 | OPENED
(1 row)
```
> Show router status in `SHOW ROUTERS` command response

- coordinator/provider/coordinator.go
- docker/tests/bin/move.sh
- qdb/etcdqdb.go
Lock/Unlock doesn't really work in coordinator, because it checks the wrong locked key range namespace in qdb. So it locks key range anyway, because we never put anything in lock/{krid}, and it never unlocks, because there is nothing in lock/keyranges/{krid}
removed `lock key range ...` from e2e test because it's done in `move key range ...` itself, so no need any preparation
```
root@spqr_client:/go# psql -h spqr_coordinator -p 7002 -U user1 -d db1
psql (13.11 (Debian 13.11-1.pgdg120+1), server 0.0.0)
Type "help" for help.
db1=> 
CREATE SHARDING RULE r1 COLUMN id;
CREATE KEY RANGE krid1 FROM 0 TO 11 ROUTE TO sh1;
CREATE KEY RANGE krid2 FROM 11 TO 31 ROUTE TO sh2;
add sharding rule                           
----------------------------------------------------------------------
created …
```
> fix lock/unlock key range wrong namespace in qdb

- coordinator/provider/coordinator.go
- test/feature/features/coordinator.feature
- test/feature/spqr_test.go
Unite:
* check shardID is the same on left and right key ranges
* check the UpperBound on the left key range matches LowerBound on the right key range
Split:
* check that bound is not less than lower bound
* check that bound is not greater than or equal to upper bound
> add some checks to Split/Unite

- cmd/coordinator/main.go
- coordinator/provider/coordinator.go
- go.mod
- go.sum
- pkg/coord/local/clocal.go
- pkg/datatransfers/data_transfers.go
- pkg/datatransfers/data_transfers_test.go
- qdb/etcdqdb.go
- qdb/memqdb.go
- qdb/memqdb_test.go
- qdb/models.go
- qdb/qdb.go
- test/feature/spqr_test.go
Split qdb interface into smaller ones.
Qdb is interface for key range and sharding rule operations. However, we also need extended QDB interface to keep routers of spqr installation, key-range move operation status etc.
> Refactor QDB interfaces, add comments to code

- coordinator/provider/coordinator.go
- qdb/etcdqdb.go
- qdb/memqdb.go
- qdb/ops/ops.go
- test/feature/features/coordinator.feature
* Implemented `CheckLockedKeyRange` in etcdQDB
* Adding sharding rule with checks
* Check if key range is locked when modifying
* Added tests
> check if sharding rule already exists

- coordinator/provider/coordinator.go
- qdb/ops/ops.go
- test/feature/features/coordinator.feature
* added feature tests for adding intersecting key range
* fix adding existing krid by splitting
* fix moving key range to the same shardID
If you move key range to the same shardID, it will return an error with the following message: `ERROR:  ERROR: transaction identifier "sh2-krid4" is already in use (SQLSTATE 42710)`. So I thought it's kinda pointless to move to the same shard and added another check.
Also when adding a new key range, one case of ranges intersection was uncovered - when you add a key range that's inside another existing key range. Thus this key range is added, but they actually intersect.
> fix key range intersection checks

- coordinator/provider/coordinator.go
- qdb/etcdqdb.go
Why do we mark status of MoveKeyRange as completed in qdb instead of just removing it? Completed operations just pollute qdb, don't they?
> fix coordinator crash when moving key range twice

- .github/scenario_balancer.py
- .github/workflows/tests.yaml
- Makefile
- docker-compose.yaml
- docker/slicer/DocStringSupport.patch
- docker/slicer/Dockerfile
- docker/slicer/slicer.js
- test/feature/spqr_test.go
Currently feature tests run in parallel in CI. But this take about 20 min, because a big feature file (e.g. Coordinator.feature). This pull request split big feature files automatically at runtime.
I have a question:
1) Is it OK to use external dependency https://github.com/bbc/cucumber-slicer.git and patch it with patch file?
Also there are a problem I discovered:
1) Overhead of creating new jobs is about 4 minutes, so if we will have a lot feature files in the future, it would be better to not split them.
2) This repo seems only run 20 jobs in parallel, while in my fork it I can run 40 jobs
> Parallelize scenarios

- coordinator/provider/coordinator.go
- test/feature/features/coordinator.feature
- test/feature/features/move.feature
* Check if key range exists
* Add tests for non-existent key range scenario and non-existent shard scenario
* Fixed typo
If we encounter an error when moving data from shard to shard, record in qdb will be marked as completed anyway. As stated in #282, we need these records to "decide key-range configuration more efficiently and precise", but actually there was no data movement. It may lead us to wrong decision. What you think?
> add checks to move key range

- pkg/meta/meta.go
- router/frontend_test.go
The real reason for failed tests are unrealized methods in pkg/coord/adapter.go.
This will be fixed in #376
> Feature tests temporary fix

- Makefile
I noticed there are so many scenarios in feature tests that github actions workers just aren't enough to run all the splitted scenarios.
I propose run each feature file separately and do not split anything. At least for now.
> fastfix: run all feature tests

- balancer/pkg/console.go
- balancer/pkg/db.go
- balancer/pkg/installation.go
- coordinator/provider/coord_pool.go
- coordinator/provider/coordinator.go
- coordinator/provider/keyranges.go
- coordinator/provider/topology.go
- pkg/clientinteractor/interactor.go
- pkg/coord/adapter.go
- pkg/models/spqrerror/spqrerror.go
- pkg/pool/conn_keeper.go
- qdb/etcdqdb.go
- qdb/memqdb.go
- qdb/ops/ops.go
- router/client/client.go
- test/regress/tests/console/expected/add.out
Replace fmt.Errorf to SpqrError where it is useful
> Change error resp

- qdb/etcdqdb.go
```{"level":"warn","ts":"2024-04-02T11:28:53.793541Z","logger":"etcd-client","caller":"v3@v3.5.12/lease.go:535","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
{"level":"warn","ts":"2024-04-02T11:28:53.79357Z","logger":"etcd-client","caller":"v3@v3.5.12/lease.go:535","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
{"level":"warn","ts":"2024-04-02T11:28:54.293437Z","logger":"etcd-client","caller":"v3@v3.5.12/lease.go:535","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
{"level":"warn","ts":"2024-04-02T11:28:54.293501Z","logger":"etcd-client","caller":"v3@v3.5.12/lease.go:535","msg":"lease keepalive response queue …
```
> revoke lease when other coordinator is active

- Makefile
run clean_feature_test before feature_test to cleanup from possible previous failed  run
> Enhance Makefile clean_feature_test targets

- Makefile
- docker-compose.yaml
- docker/router/cfg.yaml
- docker/router/cfg2.yaml
Remove client from `make run`
Remove world shard from router configs (I haven't found it's used anywhere)
Added router log file in root `docker-compose` file
> Fix make run

- pkg/clientinteractor/interactor.go
- test/feature/features/coordinator.feature
- test/feature/features/memqdb.feature
- test/feature/features/proxy_console.feature
- test/regress/tests/console/expected/add.out
- test/regress/tests/console/expected/delete_distribution.out
- test/regress/tests/console/expected/drop.out
- test/regress/tests/console/expected/hash.out
- test/regress/tests/console/expected/show_distributions.out
- test/regress/tests/console/expected/show_key_ranges.out
- test/regress/tests/console/expected/show_relations.out
- test/regress/tests/console/expected/show_routers.out
- test/regress/tests/console/expected/show_shards.out
- test/regress/tests/coordinator/expected/coordinator.out
- test/regress/tests/router/expected/alter_distribution.out
- test/regress/tests/router/expected/begin.out
- test/regress/tests/router/expected/copy_routing.out
- test/regress/tests/router/expected/error.out
- test/regress/tests/router/expected/joins.out
- test/regress/tests/router/expected/mixed_routing.out
- test/regress/tests/router/expected/multishard.out
- test/regress/tests/router/expected/shard_routing.out
- test/regress/tests/router/expected/single_shard_joins.out
- test/regress/tests/router/expected/target_session_attrs.out
- test/regress/tests/router/expected/transactions.out
- test/regress/tests/router/expected/with_tables.out
[Issue 398](https://github.com/pg-sharding/spqr/issues/398). У SPQR роутера и координатора есть административная консоль, в которой можно настраивать правила шардирования. Настройка происходит в консоли в формате запрос->ответ, и сейчас эти ответы не очень user-friendly. Надо изменить формат сообщений.
> better console messages

- docs/Authentication.md
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/config/auth_backend.go
- pkg/config/router.go
- pkg/datashard/datashard.go
-Add a different auth configuration struct for backend auth rules (because AuthMethod is not used here).
-Add the ability to use different usernames when internal backend connects to shards. 
This may be used when:
- Different shards have different PostgreSQL usernames.
- When using LDAP/GSS auth - SPQR as one entrypoint for many LDAP users able to connect.
>  Able to use different username when internal backend connect to shards

- pkg/meta/meta.go
- pkg/models/spqrerror/spqrerror.go
- router/grpc/qrouter.go
- router/qrouter/proxy_routing.go
There is no `sharding rule` term anymore
```
regress=> create table denchick(i int);
ERROR:  client proccessing error: error processing query 'create table denchick(i int);': failed to match query to any sharding rule, tx status IDLE
```
> Drop `sharding rule` mentions

- go.mod
- go.sum
- router/frontend/frontend_test.go
- router/qrouter/proxy_routing.go
- router/qrouter/proxy_routing_test.go
- router/relay/relay.go
- router/server/multishard.go
- test/regress/tests/router/expected/copy_routing.out
- test/regress/tests/router/sql/copy_routing.sql
I suggest routing COPY command according to data to be copied. We parse the data, then get route for each row and compare. For now support only routing to one shard, which means if routes are different, return error.
> Support COPY

- pkg/clientinteractor/interactor.go
- pkg/meta/meta.go
- test/feature/features/coordinator_show.feature
- yacc/console/ast.go
- yacc/console/gram.go
- yacc/console/gram.y
- yacc/console/lex.go
- yacc/console/yx_test.go
Tried to make it in more generic way, just in case we want to group in some other queries.
If group by is specified, column and count is returned
> Group by in Coordinator SHOW

- pkg/session/dummy_holder.go
- pkg/session/param.go
- router/client/client.go
- router/mock/client/mock_client.go
- router/qrouter/proxy_routing.go
- router/relay/qstate.go
Also `__spqr__distribution_key`
```
db1=# \c spqr-console
SPQR router admin console
Here you can configure your routing rules
------------------------------------------------
You can find documentation here
https://github.com/pg-sharding/spqr/tree/master/docs
psql (16.2 (Ubuntu 16.2-1.pgdg20.04+1), server console)
WARNING: psql major version 16, server major version 0.0.
Some psql features might not work.
You are now connected to database "spqr-console" as user "reshke".
spqr-console=> show relations;
Relation name | Distribution ID | Distribution key
---------------+-----------------+------------------
t             | ds1             | ("i", identity)
t22           | ds1             | ("i", identity)
(2 rows)
spqr-console=> \c db1
psql (16.2 (Ubuntu 16.2-1.pgdg20.04+1), server 15.4)
You …
```
> Support __spqr__auto_distribution hint

- .github/workflows/linters.yaml
- Makefile
- pkg/client/clientpool.go
- pkg/config/balancer.go
- pkg/config/coordinator.go
- pkg/decode/spqrql_test.go
- pkg/meta/meta.go
- pkg/pool/dbpool.go
- pkg/pool/dbpool_test.go
- pkg/pool/shardpool_test.go
- qdb/memqdb_test.go
- router/rulerouter/rulerouter.go
- script/gofmtcheck.sh
Introduce 2 brand-new commands: `make fmtcheck` and `make fmt`.
make fmcheck failed:
```
➜  spqr git:(denchick-journey-5) ✗ make fmtcheck
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./pkg/config/coordinator.go
./pkg/config/balancer.go
./pkg/meta/meta.go
./pkg/decode/spqrql_test.go
./pkg/pool/shardpool_test.go
./pkg/pool/dbpool.go
./pkg/client/clientpool.go
You can use the command: `make fmt` to reformat code.
make: *** [fmtcheck] Error 1
```
make fmcheck passed:
```
➜  spqr git:(more-linters) ✗ make fmtcheck
==> Checking that code complies with gofmt requirements...
OK
```
> Add go fmt check

- router/app/app.go
- test/feature/conf/router.yaml
- test/feature/conf/router_cluster.yaml
- test/feature/conf/router_coordinator.yaml
- test/feature/conf/router_coordinator_2.yaml
- test/feature/conf/router_with_backup.yaml
- test/feature/conf/router_with_backup_and_initsql.yaml
- test/feature/conf/router_with_coordinator.yaml
- test/feature/conf/router_with_fake_initsql_and_backup.yaml
- test/feature/conf/router_with_gss_frontend.yaml
- test/feature/conf/router_with_initsql.yaml
- test/feature/conf/router_with_initsql_and_coordinator_init.yaml
- test/feature/conf/router_with_ldap_frontend.yaml
- test/feature/conf/router_with_scram_backend.yaml
- test/feature/conf/router_with_scram_frontend.yaml
- test/feature/docker-compose.yaml
- test/feature/features/coordinator_show.feature
Listening localhost by default was added in https://github.com/pg-sharding/spqr/commit/2b741a36fd954a80ebc0c7947076c39c0dbaa48f
If I set host in config to empty string (to listen to all addresses), there's a race between goroutines to take the address
If you want to connect to spqr on localhost, use unix socket
> do not listen localhost by default

- coordinator/app/app.go
- coordinator/provider/coordinator.go
But if host is empty string, then put hostname into qdb as coordinator address
> do not listen localhost by default in coordinator

- coordinator/provider/shards.go
- pkg/datashard/datashard.go
- pkg/mock/shard/mock_shard.go
- pkg/shard/shard.go
- router/mock/poolmgr/mock_pool_mgr.go
- router/mock/server/mock_server.go
- router/poolmgr/pool_mgr.go
- router/relay/relay.go
- router/server/multishard.go
- router/server/server.go
- router/server/shard.go
It was added in https://github.com/pg-sharding/spqr/pull/679.
On the one hand, there are no calls to .RequestData(). On the other hand, the only real implementation of RequestData is here (https://github.com/pg-sharding/spqr/blob/master/pkg/datashard/datashard.go#L102). As you can see, it is completely useless. So, we may safely delete all mentions of RequestData.
> Drop RequestData()

- cmd/worldmock/worldmock.go
- coordinator/provider/coordinator.go
- router/client/client.go
How It was:
```
{"level":"info","ssl":true,"time":"2024-12-26T12:33:10Z","message":"init client connection"}
{"level":"info","user":"spqr-console","db":"spqr-console","time":"2024-12-26T12:33:10Z","message":"initialized client connection"}
```
How it became:
```
{"level":"info","ssl":true,"time":"2024-12-26T12:33:10Z","message":"init client connection"}
{"level":"info","user":"spqr-console","db":"spqr-console", "ssl":true, "time":"2024-12-26T12:33:10Z","message":"init client connection OK"}
```
> Minor enhancement of coordinator log messages

- cmd/spqrdump/main.go
- pkg/config/tls.go
In this PR:
- add comments in `pkg/config/tls.go` to not forget why we use `InsecureSkipVerify: true`.
- add InsecureSkipVerify flag to spqr-dump tool.
```
➜  spqr git:(comment-potential-security-problems) ✗ ./spqr-dump --help
Usage:
spqr-dump [command]
Available Commands:
dump        dump current sharding configuration
help        Help about any command
Flags:
-e, --endpoint string        endpoint for dump metadata (default "localhost:7000")
-h, --help                   help for spqr-dump
--insecure-skip-verify   skip TLS certificate verification
-l, --log-level string       log level (default "error")
-p, --passwd string          password to use for communication
-t, --proto string           protocol to use for communication (default "grpc")
Use "spqr-dump [command] --help" for more …
```
> Explain InsecureSkipVerify

- router/frontend/frontend_test.go
- router/mock/qrouter/mock_qrouter.go
- router/pgcopy/state.go
- router/qrouter/proxy_routing.go
- router/qrouter/qrouter.go
- router/relay/relay.go
- router/rmeta/rmeta.go
>  Refactor query routing internals. Separate rmeta-related logic. 

- go.mod
- go.sum
- router/qrouter/proxy_routing.go
- test/regress/schedule/router
- test/regress/tests/router/expected/ddl.out
- test/regress/tests/router/expected/target_list_routing.out
- test/regress/tests/router/sql/ddl.sql
- test/regress/tests/router/sql/target_list_routing.sql
Also bump lyx with NOT IN support.
> Support routing based purely on target list.

- router/frontend/frontend_test.go
- router/mock/server/mock_server.go
- router/plan/plan.go
- router/qrouter/local.go
- router/qrouter/proxy_routing.go
- router/qrouter/proxy_routing_test.go
- router/relay/phs.go
- router/relay/relay.go
- router/rmeta/rmeta.go
- router/server/multishard.go
- router/server/server.go
- router/server/shard.go
- test/regress/tests/router/expected/begin.out
- test/regress/tests/router/expected/copy_inside_singleshard_connection.out
- test/regress/tests/router/expected/ddl.out
- test/regress/tests/router/expected/engine_v2.out
- test/regress/tests/router/expected/error2.out
- test/regress/tests/router/expected/multishard_expand_tx.out
- test/regress/tests/router/expected/transactions.out
- test/regress/tests/router/sql/multishard_expand_tx.sql
For example, after establishing multi-shard slice connection (say, ddl), we should still route single-shard modification sql (insert for example) to its execution target
> Execute expanded transaction query on specified execution targets

- cmd/router/main.go
- pkg/spqrlog/zero.go
Even with color in your console!
```
➜  spqr git:(master) ✗ ./spqr-router run --config examples/1shardproxy.toml
...
{"level":"info","address":"localhost:7432","time":"2025-02-24T14:42:28+01:00","message":"SPQR Administative Console is ready on"}
{"level":"info","address":"localhost:6432","time":"2025-02-24T14:42:28+01:00","message":"SPQR Router is ready by postgresql proto"}
{"level":"info","address":"localhost:7001","time":"2025-02-24T14:42:28+01:00","message":"SPQR GRPC API is ready on"}
➜  spqr git:(master) ✗ ./spqr-router run --config examples/1shardproxy.toml --pretty-log
...
2:43PM DBG creating QueryRouter with type qtype=config.RouterMode
2:43PM INF adding node node=sh1
2:43PM DBG memqdb: add shard shard={"hosts":["localhost:5432"],"id":"sh1"}
2:43PM DBG adding frontend rule …
```
> `spqr-router run [-P|--pretty-log]` enables pretty logging

- cmd/coordinator/main.go
- docs/configuration/coordinator.mdx
- pkg/config/coordinator.go
- pkg/spqrlog/zero.go
This PR resolves several problems with coordinator logs.
1. Now you can specify log format using pretty-log flag:
```
➜  spqr git:(master) ✗ ./spqr-coordinator --config ./examples/coordinator.yaml --qdb-impl etcd --pretty-log     
2025/03/11 18:17:31 Running config: {
...
}
2025/03/11 18:17:31 unknown log level: ddebug, defaulting to info
6:17PM INF running coordinator app
6:17PM ERR qdb already taken, waiting for connection error="qdb is already in use."
6:17PM ERR qdb already taken, waiting for connection error="qdb is already in use."
6:17PM ERR qdb already taken, waiting for connection error="qdb is already in use."
```
2. Now it allows to specify log level:
```
➜  spqr git:(master) ✗ ./spqr-coordinator --config ./examples/coordinator.yaml --qdb-impl etcd --log-level debug …
```
> Better options for coordinator logging

- qdb/etcdqdb.go
How it became:
```
{"level":"debug","key-range":{"from":["AgAAAAAAAAA="],"shard_id":"sh1","key_range_id":"krid1","distribution_id":"ds1"},"time":"2025-03-14T17:34:27Z","message":"memqdb: add key range"}
```
> Minor etcdqdb log enhancement

- pkg/coord/cqdb.go
- pkg/mock/meta/mock_meta.go
- pkg/models/kr/keyrange.go
- router/mock/client/mock_client.go
- router/mock/poolmgr/mock_pool_mgr.go
- router/mock/server/mock_server.go
- yacc/console/gram.go
- yacc/console/gram.y
- yacc/console/lex.go
- yacc/console/yx_test.go
issue 1154. PutVarint needs buf[binary.MaxVarintLen64=10] to avoid panic in case big numbers
(https://pkg.go.dev/encoding/binary#PutVarint)
> fix buf size for PutVarint

- qdb/ops/ops.go
- qdb/ops/ops_test.go
incorrect check of intersection for key_range which lets create doubles
example:
3 runs init2shards.sql gets memqdb_with_doubles.json
[memqdb_with_doubles.json](https://github.com/user-attachments/files/20694412/memqdb_with_doubles.json)
> key range doubles

- pkg/workloadreplay/workloadreplay.go
fix false alarm feature test workloadlog.feature
"
Scenario: WorkloadReplay replays logs 
"""
002
"""
actual value '[]' doesn't match expected '002', actual value '[]' doesn't match expected '002'
"
> fix false alarm workload test

- yacc/console/gram.go
- yacc/console/gram.y
Not only this rule is impossible to invoke due to how console's parser deal with `REPLICATED` token, but also considered harmfull
> Remove unused and harmfull reference relation definition rule

- pkg/coord/clustered_coord.go
- qdb/etcdqdb.go
- qdb/memqdb.go
- qdb/mock/qdb.go
- qdb/qdb.go
- test/feature/features/coordinator.feature
- test/feature/spqr_test.go
Now if coordinator lose lock, it won't try to retake it and will keep acting like primary coordinator. This may happen due to etcd restart, for example.
> Coordinator retake lock

- pkg/models/kr/keyrange.go
```
7:49AM DBG closing client client-id=824636656896
7:49AM DBG failed to close netconn error="close tcp 192.168.107.3:6432->192.168.107.1:53678: use of closed network connection"
panic: unknown column type
goroutine 87 [running]:
github.com/pg-sharding/spqr/pkg/models/kr.(*KeyRange).RecvFunc(0xc0000cd2a0, 0x0, {0xc000045a10, 0x24})
/spqr/pkg/models/kr/keyrange.go:141 +0x457
github.com/pg-sharding/spqr/pkg/models/kr.(*KeyRange).RecvRaw(0xc0000cd2a0, {0xc0000cd620, 0x1, 0x1})
/spqr/pkg/models/kr/keyrange.go:170 +0x134
github.com/pg-sharding/spqr/pkg/models/kr.KeyRangeBoundFromStrings({0xc000616690, 0x1, 0x1}, {0xc0000cd620, 0x1, 0x1})
/spqr/pkg/models/kr/keyrange.go:184 +0x14a
github.com/pg-sharding/spqr/router/rmeta.(*RoutingMetadataContext).ResolveRouteHint(0xc00040c180, {0x1c474b8, …
```
> fix panic: unknown column type

- .github/actions/spelling/expect.txt
- pkg/meta/meta.go
Able to get rid of the last `nolint` directives
> Use spqrerror.Newf instead of fmt.Errorf in meta.go

- pkg/pool/dbpool.go
- pkg/pool/dbpool_test.go
The main purpose is to rearrange host selection logic to convert all backend feedback (aliveness, replication lag, etc) into single priority number, and run selection algorithm on numbers.
This is just an preparational patch; no behavioural changes is expected/intended
> Introduce priority-based host selection logic.
