pg-sharding/spqr

router/pkg/qrouter/proxy.go
test/regress/expected/shard_routing.out
test/regress/run_tests.sh
test/regress/sql/shard_routing.sql

Also add more sql regression queries to simple_routing test

Fix buf with values-based insert statement routing

---

pkg/conn/auth.go
router/pkg/client/client.go

Continue client-sever intercation after ssl requirest rejection Send ssl negotionation message and wait for next client message. Also fix incorrect auth rule handling in AuthBackend()

Do not close connection with disabled ssl

---

qdb/mem/mem.go
router/pkg/frontend.go
router/pkg/parser/qparser.go
router/pkg/qrouter/local.go
router/pkg/qrouter/proxy.go
router/pkg/qrouter/proxy_routing.go
router/pkg/qrouter/qrouter.go
router/pkg/rulerouter/relay.go
router/pkg/server/multishard.go

Fix simultanious access to qrouter parser
move qparser to relay structure internals.
Refactor code accordingly.

Fix simultanious access to qrouter parser

---

qdb/mem/mem.go
router/pkg/qrouter/proxy.go

Revert "Allow dataspace create & list in local proxy router setup"

---

router/pkg/qrouter/proxy_routing.go

forbit routing of router-indistinguishable column refencies

Restrict routing of the complex from-clause queries

---

coordinator/provider/coordinator.go
pkg/models/shrule/shardingrule.go
qdb/etcdqdb.go
qdb/memqdb.go
qdb/models.go
test/regress/tests/console/expected/show_sharding_rules_1.out
test/regress/tests/console/expected/show_sharding_rules_2.out

Sort results of List request to qdb 

---

balancer/pkg/console.go
router/pkg/client/client.go
router/pkg/console/console.go
router/pkg/rulerouter/relay.go
yacc/console/sql.y

```
router_1       | ERROR: 2023/01/16 10:18:41.564858 got unexpected postgresql proto message with type *pgproto3.Terminate
3077
router_1       | ERROR: 2023/01/16 10:18:41.564868 unexpected EOF
```

remove annoying log messages

---

balancer/pkg/console.go
coordinator/provider/coordinator.go
pkg/clientinteractor/interactor.go
pkg/meta/meta.go
router/pkg/console/console.go
router/pkg/frontend.go
router/pkg/parser/qparser.go
router/pkg/qrouter/explain.go

Explain feaure should tell client, for each query, why is this query routed to its shards, and what are sharding keys/key ranges of given query

Explain feature basics.

---

cmd/coordinator/main.go
coordinator/provider/coordinator.go
pkg/clientinteractor/interactor.go
pkg/meta/meta.go
pkg/models/topology/routers.go
pkg/models/topology/shards.go
pkg/spqrlog/log.go
qdb/etcdqdb.go
qdb/memqdb.go
router/pkg/qrouter/proxy.go

It is usefull for local setup and testing to use mem qdb sometimes.

Add cli option to coordinator to select running qdb implementation

---

pkg/conn/auth.go

Password for backend auth may be stored in encrypted way for md5, to hide original passwd string

Allow encrypted password for backend auth in config

---

cmd/router/main.go
config-example/localrouter.yaml
go.mod
go.sum
pkg/config/router.go
pkg/conn/auth.go

Also fix md5-password reuse check

Add daemonize router feature

---

config-example/localrouter.yaml
coordinator/app/app.go
router/app/app.go

This helps to access router from local machine without additional configure

Listen localhost in psql-proto by default

---

router/pkg/datashard/conn_pool.go

Keep trying on other cluster hosts

Do not raise error if shard host is down

---

cmd/spqrdump/main.go
pkg/decode/spqrql.go

```
reshke@oheijweoij:~/spqr2/cmd$ ./sdump dump -e 'localhost:7777'
CREATE SHARDING RULE r1 COLUMN w_id;
CREATE SHARDING RULE r2 COLUMN id;
CREATE SHARDING RULE r3 COLUMN bid;
CREATE KEY RANGE krid1 FROM 1 TO 10 ROUTE TO sh1;
CREATE KEY RANGE krid2 FROM 11 TO 20 ROUTE TO sh1;
CREATE KEY RANGE krid3 FROM 21 TO 30 ROUTE TO sh2;
```

Add spqrdump tool

---

examples/auth_supported.yaml
examples/localrouter.yaml
examples/router.yaml
pkg/auth/auth.go
pkg/config/router.go
router/rule/rulemgr.go
test/authentification/auth_test.go

Added backward compatibility with old router configs

Default auth rule

---

Makefile
cmd/router/main.go
docker/spqr/Dockerfile
pkg/clientinteractor/interactor.go
pkg/meta/meta.go
pkg/version.go
test/regress/schedule/console
test/regress/tests/console/expected/show_version.out
test/regress/tests/console/sql/show_version.sql
yacc/console/ast.go
yacc/console/reserved_keyword.go
yacc/console/sql.go
yacc/console/sql.y

```
➜  spqr git:(add-version) ./spqr-router --version
spqr-router version 0.0.5-c0edd4e
```
```
db=> SHOW version;
SPQR version 
----------------
0.0.5-c0edd4e
```

Show version in command-line and console

---

.github/workflows/release.yaml
Makefile
debian/changelog

Replace version number in debian/control correctly

Fix release job

---

coordinator/provider/coordinator.go
coordinator/provider/keyranges.go
pkg/coord/local/clocal.go
pkg/meta/meta.go
pkg/models/kr/keyrangemgr.go
router/grpc/qrouter.go

lock and unlock only once in Move
and change method name in interface to be more consistent

fix double lock key range on router when moving data

---

pkg/datatransfers/data_transfers.go

earlier, when executing the MOVE command, the data was first downloaded and only then loaded. This is not efficient and possibly can lead to deadlock if pipe overflows.
<details>
<summary>Steps to reproduce</summary>
1. `make run`
2. run in client container:
```bash
#!/bin/bash
set -x
N=1000000
psql "host=spqr_coordinator sslmode=disable port=7002" -c "REGISTER ROUTER r1 ADDRESS spqr_router_1_1:7000;"
psql "host=spqr_coordinator sslmode=disable user=user1 dbname=db1 port=7002" -c "DROP KEY RANGE ALL;"
psql "host=spqr_coordinator sslmode=disable user=user1 dbname=db1 port=7002" -c "ADD KEY RANGE krid1 FROM 1 TO $N ROUTE TO sh1;"
psql "host=spqr_coordinator sslmode=disable user=user1 dbname=db1 port=7002" -c "ADD KEY RANGE krid2 FROM $((N+1)) TO $((2*N)) ROUTE TO sh2;"
psql …
```

fix possible deadlock on big move

---

cleanup-docker.sh
go.mod
go.sum
pkg/datashard/datashard.go
pkg/pool/shardpool.go
pkg/tsa/tsa.go
router/client/client.go
router/frontend.go
router/frontend_test.go
router/mock/client/mock_client.go
router/poolmgr/pool_mgr.go
router/relay/relay.go
router/route/routemgr.go
router/server/multishard.go
router/server/shard.go
test/regress/tests/router/expected/error.out
test/regress/tests/router/expected/joins.out
test/regress/tests/router/expected/shard_routing.out
test/regress/tests/router/expected/single_shard_joins.out

Basic support of extended query protocol interactions.

Xproto: extended query protocol interactions.

---

router/console/console.go

https://github.com/psycopg/psycopg2/blob/master/psycopg/connection_int.c#L647

Add dataStyle to router console

---

test/regress/schedule/router
test/regress/tests/router/expected/routing_hint.out
test/regress/tests/router/sql/routing_hint.sql

Add test to @reshke task(add router_hint)

add test to router_hint

---

pkg/models/kr/keyrange.go
qdb/ops/ops.go
test/regress/tests/router/expected/shard_routing.out
test/regress/tests/router/sql/shard_routing.sql

Revert "Add inf support"

---

test/regress/schedule/console
test/regress/tests/console/expected/show_clients.out
test/regress/tests/console/sql/show_clients.sql

We already testing `SHOW clients` in feature tests. Anyway, I think it's a good idea to add them to regress too.

Simple `SHOW clients` tests

---

qdb/etcdqdb.go

```
{"level":"warn","ts":"2024-01-11T08:13:54.756157+0300","logger":"etcd-client","caller":"v3/lease.go:535","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
{"level":"warn","ts":"2024-01-11T08:13:55.757264+0300","logger":"etcd-client","caller":"v3/lease.go:535","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
{"level":"warn","ts":"2024-01-11T08:13:56.758495+0300","logger":"etcd-client","caller":"v3/lease.go:535","msg":"lease keepalive response queue is full; dropping response send","queue-size":16,"queue-capacity":16}
{"level":"warn","ts":"2024-01-11T08:13:57.760101+0300","logger":"etcd-client","caller":"v3/lease.go:535","msg":"lease keepalive response queue is full; …
```

Consume message from Lease.KeepAlive channel in TryLockCoordinator

---

coordinator/app/app.go
coordinator/provider/coordinator.go
docker/coordinator/cfg.yaml
examples/coordinator.yaml
pkg/config/coordinator.go
qdb/etcdqdb.go
test/feature/conf/coordinator.yaml
test/feature/conf/coordinator2.yaml
test/feature/conf/router_coordinator.yaml
test/feature/conf/router_coordinator_2.yaml
test/regress/conf/coordinator.yaml

Like in router https://github.com/pg-sharding/spqr/blob/master/pkg/config/router.go#L50

Rename http_addr to grpc_api_port in coordinator

---

cmd/coordinator/main.go
cmd/router/main.go
coordinator/provider/coordinator.go
docker/coordinator/cfg.yaml
examples/coordinator.yaml
pkg/auth/auth.go
pkg/config/coordinator.go
router/console/console.go
router/instance.go
test/feature/conf/coordinator.yaml
test/feature/conf/coordinator2.yaml
test/feature/conf/router_coordinator.yaml
test/feature/conf/router_coordinator_2.yaml
test/feature/spqr_test.go
test/regress/conf/coordinator.yaml

Seem working
```
➜  spqr git:(make-coordinator-auth-again) ✗ psql "host=localhost port=7002 dbname=spqr-console user=spqr-console"
Password for user spqr-console: 
psql (14.10 (Homebrew), server 0.0.0)
Type "help" for help.
spqr-console=> SHOW sharding_rules;
Sharding Rule ID | Dataspace ID | Table Name | Columns | Hash Function 
------------------+--------------+------------+---------+---------------
(0 rows)
spqr-console=> ^C
spqr-console=> 
\q
➜  spqr git:(make-coordinator-auth-again) ✗ psql "host=localhost port=7002 dbname=spqr-console user=spqr-consoled"
^C
```

Coordinator auth

---

router/qrouter/proxy_routing.go
test/xproto/proto_test.go

Tests executed by professional. Dont try this on your own.
```
reshke@oheijweoij:~/spqr/test/xproto$ POSTGRES_HOST=localhost POSTGRES_PORT=6432 go test . -count=1
ok  	github.com/pg-sharding/spqr/test/xproto	0.051s
```

Fix some xproto tests

---

pkg/meta/meta.go
test/regress/tests/console/expected/delete_distribution.out
test/regress/tests/console/sql/delete_distribution.sql

Detach relations in DROP DISTRIBUTION CASCADE

---

pkg/session/dummy_holder.go
pkg/session/param.go
pkg/spqrlog/zero.go
router/client/client.go
router/frontend/frontend_test.go
router/mock/client/mock_client.go
router/relay/qstate.go
router/relay/relay.go
router/server/multishard.go

This is POC parts of this patch series, without any perf enhancements and/or 2pc commit

Allow multishard copy under separate setting

---

router/qrouter/proxy_routing.go

https://github.com/pg-sharding/spqr/discussions/800

Support for pg_catalog - only queries

---

coordinator/provider/coordinator.go
pkg/client/clientpool.go
pkg/clientinteractor/interactor.go
pkg/clientinteractor/interactor_test.go
pkg/conn/instance.go
pkg/datashard/datashard.go
pkg/meta/meta.go
pkg/shard/shard.go
router/client/client.go
router/console/console.go
router/frontend/frontend.go
router/frontend/frontend_test.go
router/grpc/qrouter.go
router/mock/client/mock_client.go
router/qrouter/local.go
router/route/route.go
router/rulerouter/route_pool.go
router/rulerouter/rulerouter.go
router/server/multishard.go
router/server/shard.go

This reverts commit be43df84adb6421846b64b18abaff7d819769ccd.

Revert "Drop some dead code (#828)" to fix feature tests

---

pkg/pool/dbpool.go

in "failed to get connection to any shard host" error

Correctly separate host error messages

---

cmd/balancer/main.go
cmd/coordinator/main.go
cmd/router/main.go
pkg/config/balancer.go
pkg/config/coordinator.go
pkg/config/router.go
router/rulerouter/rulerouter.go

This command read, validates, then prints the given config file.
Resolves #844

Add test-config command to SPQR binaries

---

docs/sharding/console/sql_commands.mdx

add INVALIDATE CACHE command to docs

---

coordinator/provider/coordinator.go
pkg/config/coordinator.go

Fixes https://github.com/pg-sharding/spqr/issues/897

Watch routers iteration timeout

---

go.mod
go.sum
pkg/client/client.go
pkg/mock/meta/mock_meta.go
pkg/session/dummy_holder.go
pkg/session/param.go
router/client/client.go
router/frontend/frontend_test.go
router/mock/client/mock_client.go
router/qrouter/proxy_routing.go
router/qrouter/proxy_routing_test.go
router/relay/phs_test.go
router/relay/qstate.go
router/relay/relay.go
router/rulerouter/rulerouter.go
router/server/shard.go
test/regress/tests/router/expected/routing_hint.out
test/regress/tests/router/sql/routing_hint.sql
test/xproto/proto_test.go

Better virtual GUC management + tests

Virtual param fixes

---

docs/sharding/console/sql_commands.mdx

Add REDISTRIBUTE command documentation

---

coordinator/provider/coordinator.go
pkg/clientinteractor/interactor.go
pkg/connectiterator/connectiterator.go
pkg/meta/meta.go
router/console/console.go
router/instance/instance.go
router/rulerouter/rulerouter.go
yacc/console/ast.go
yacc/console/gram.go
yacc/console/gram.y
yacc/console/yx_test.go

```
spqr-console=> show instance;
total tcp connection count | total cancel requests | active tcp connections
----------------------------+-----------------------+------------------------
5                          | 1                     | 1
(1 row)
spqr-console=> ^C
```

Add `show instance` support

---

router/relay/relay.go
test/xproto/proto_test.go

Actually save statement description

Fix preparing multishard DDL statement

---

docs/mint.json
docs/sharding/copy.mdx

Add COPY FROM documentation

---

router/relay/relay.go

Should never happen, but still check.

Fix possible null dereference.

---

go.mod
go.sum
router/qrouter/proxy_routing_test.go

Add test for this feature also.

Support schema-qualified column reference routing

---

router/relay/relay.go
router/server/multishard.go
test/regress/schedule/router
test/regress/tests/router/expected/multishard_expand_tx.out
test/regress/tests/router/sql/multishard_expand_tx.sql

Add regression test to illustrate current behavior

Expand transaction part2

---

balancer/app/app.go
cmd/balancer/main.go
cmd/router/main.go
cmd/spqrdump/main.go
examples/1shardproxy.toml
pkg/spqrlog/zero.go
router/rulerouter/rulerouter.go

Add logLevel to spqrlog.ReloadLogger, get rid of spqrlog.UpdateZeroLogLevel

Minor spqrlog.ReloadLogger refactoring

---

examples/4shardproxy.yaml

Make example config works for regression tests

Update 4shardproxy.yaml: add schema cache backend rule

---

coordinator/mock/mock_coordinator.go
pkg/coord/adapter.go
pkg/coord/clocal.go
pkg/coord/clocal_test.go
pkg/coord/coord.go
pkg/coord/cqdb.go
pkg/meta/meta.go
pkg/mock/meta/mock_meta.go
pkg/models/rrelation/rmgr.go
pkg/models/rrelation/rrelation.go
yacc/console/ast.go
yacc/console/gram.go
yacc/console/gram.y
yacc/console/yx_test.go

Use separate code paths for reference relation handling. Do abandon auto-increment feature for distributed relations for now.

Optimize and refactor reference relation handling

---

yacc/console/gram.go
yacc/console/gram.y
yacc/console/lex.go
yacc/console/lex.rl
yacc/console/lx_test.go
yacc/console/yx_test.go

0) fixed incorrect succesfull parsing incorrect int values; 
1) fixed error on left int64 border -9223372036854775808  .

int parsing ussues are fixed

---

pkg/meta/meta.go

preliminary change for issue: https://github.com/pg-sharding/spqr/pull/1287/

small improve testability

---

test/feature/features/reference_relation.feature

fixed for https://github.com/pg-sharding/spqr/pull/1310
may be bug in https://github.com/jmoiron/sqlx on hint-comment: /* __spqr__execute_on: sh1 */

fix feature test reference_relation.feature

---

.github/actions/spelling/excludes.txt
docker-compose.yaml
docker/coordinator/Dockerfile
docker/router/Dockerfile
docker/router/cfg.yaml
docker/router/cfg2.yaml
docker/router/entrypoint.sh
test/drivers/gorm-regress/docker-compose.yaml
test/drivers/hibernate-regress/docker-compose.yaml
test/drivers/jdbc-regress/docker-compose.yaml
test/feature/docker-compose.yaml
test/regress/docker-compose.yaml
test/stress/docker-compose.yaml
test/xproto/docker-compose.yaml
test/xproto/router/Dockerfile

Revert "Simplify docker images"

---

router/relay/relay.go

ProcQuery() already correctly takes case of BindComplete etc

Remove AddSilentQuery and its usages.

---

.github/actions/spelling/expect.txt
router/relay/relay.go
test/feature/features/prepared_stmt.feature
test/feature/spqr_test.go

panic here on insert into reference table in prepared statement

fix panic, add prepared statement feature test

---

docs/sharding/console/sql_commands.mdx
pkg/clientinteractor/interactor.go
pkg/conn/instance.go
pkg/connmgr/connmgr.go
pkg/coord/clustered_coord.go
pkg/meta/meta.go
pkg/pool/dbpool.go
pkg/pool/dbpool_cache.go
pkg/pool/pool.go
router/rulerouter/rulerouter.go
test/regress/schedule/console
test/regress/tests/console/expected/show_tsa_cache.out
test/regress/tests/console/sql/show_tsa_cache.sql
yacc/console/ast.go
yacc/console/gram.go
yacc/console/gram.y
yacc/console/yx_test.go

```
tsa       |      host      | az | alive | match |          reason          |      last_check_time      
----------------+----------------+----+-------+-------+--------------------------+---------------------------
prefer-standby | localhost:5432 |    | true  | true  | primary                  | 2025-08-29T12:52:33+02:00
any            | localhost:5432 |    | true  | true  | target session attrs any | 2025-08-29T12:51:57+02:00
(2 rows)
```

SHOW tsa_cache

---

pkg/clientinteractor/interactor.go

The command "show task_group" causes a panics. This happens due to races that occur when the movetaskgroup process is in progress.
one of kind panic example:
panic: runtime error: index out of range [0] with length 0
goroutine 39953 [running]:
github.com/pg-sharding/spqr/pkg/models/kr.KeyRangeFromBytes({0x0, 0x0, 0x0}, {0xc000fd46b0, 0x1, 0x1})
/spqr/pkg/models/kr/keyrange.go:392 +0x236
github.com/pg-sharding/spqr/pkg/clientinteractor.(*PSQLInteractor).MoveTaskGroup(0xc000a88360, {0x18a79a0, 0x20b8880}, 0xc000f52060, {0xc000fd46b0, 0x1, 0x1})
/spqr/pkg/clientinteractor/interactor.go:701 +0x946
github.com/pg-sharding/spqr/pkg/meta.ProcessShow({0x18a79a0, 0x20b8880}, 0xc000857080, {0x18c1260, 0xc00019fb80}, {0x18ad1c8, 0xc00019fb80}, 0xc000a88360, 0x0)

fix some panics
